### ISSUE TITLE
More flexible column handling

### ISSUE THREAD

**Issue by RandomString123** [RandomString123/FWF.jl#4] opened 2018-02-17 17:24 UTC
Right now the code assumes that column widths are contiguous, encompass a whole line, and can't be dropped.  So if a user only wanted the columns from 2:3 and 4:8 from a 1:16 range line the only way to do it is to make 3 columns 1:1, 2:3, 4:8, 9:16 (or 1,2,5,8) and drop the others after parsing.  The following functionality should be added to make columns more flexible:

* Allow users to select which columns they want to keep in the output.
** ex: ([1,2,5,8], [false, true, true, false])

* Allow users to input the total line length and only the ranges they want from the line.  This could just insert dummy ranges on the back-end that are not kept.  
** ex: (16, [2:3, 4:8])

A harder but possibly nicer version would be one that just accepts ranges and pads between them and auto-detects line length.

ex, assuming 16 length line:
[2:3, 8:10] -> ([1:1,2:3,4:7,8:10,11:16], [false,true,false,true,false])

**Comment by bkamins** [comment] 2018-02-18 22:05
In PR #13 I proposed an approach to this issue. I think we can omit support of the pattern `[1,2,5,8], [false, true, true, false]` as it is not very useful (one can always use ranges - in my package I had `keep` variable because I transformed ranges to widths, but here we transform widths to ranges so `keep` binary vector is not required).

I also currently allow for lines longer than the requested width to be silently accepted. If we want to avoid this this should be a relatively simple patch (but I am not sure we want it) - any opinion on this?

**Comment by RandomString123** [comment] 2018-02-18 23:41
I think allowing lines longer than requested will be fine unless someone outside of us can come up with a reason we shouldn't.  The only reason it might be a pain is column based parsing but I think whatever method we eventually come up with for that will most likely involve parsing the whole file and then only streaming it one column at a time through the interface.  It will be very difficult to come up with a method that works given all of the randomness that can exist in the file.    

I believe this item can be closed now unless you can think of any more work that needs to be done to address it.

**Comment by bkamins** [comment] 2018-02-19 15:15
I will make a PR that checks if every line has exactly the same length as this is simple. Actually the problem is that we can issue only a global warning if it does not - and this is what I will do.

E.g. consider a file from which we want to get `[1:2 5:7]` and the actual line lengths are 10, 12, 15 and 17. It is ambiguous for which lines we should decide that they are malformed. We can only say that there exists a malformed line.

So I will close this issue as you have suggested and make a PR today.

**Closed as completed by bkamins** 2018-02-19 15:15 UTC
